services:
  - type: web
    name: filestash-oidc-proxy
    env: docker
    dockerfilePath: /filestash-oidc-proxy/Dockerfile
    dockerContext: /filestash-oidc-proxy
    domains:
      - filestash.mackenzieclark.codes
    envVars:
      - key: OAUTH2_PROXY_CLIENT_ID
        sync: false
      - key: OAUTH2_PROXY_UPSTREAMS
        sync: false
      - key: OAUTH2_PROXY_REVERSE_PROXY
        value: true
      - key: OAUTH2_PROXY_PROVIDER
        value: oidc
      - key: OAUTH2_PROXY_CLIENT_SECRET
        sync: false
      - key: OAUTH2_PROXY_OIDC_ISSUER_URL
        sync: false
      - key: OAUTH2_PROXY_COOKIE_SECURE
        value: true
      - key: OAUTH2_PROXY_EMAIL_DOMAIN
        value: '*'

  - type: pserv
    name: filestash
    plan: 'starter plus'
    env: docker
    dockerfilePath: /filestash/Dockerfile
    dockerContext: /filestash
