services:
  - type: web
    name: filestash-oidc-proxy
    env: docker
    dockerfilePath: /filestash-oidc-proxy/Dockerfile
    dockerContext: /filestash-oidc-proxy
    domains:
      - filestash.mackenzieclark.codes
  - type: pserv
    name: filestash
    plan: 'starter plus'
    env: docker
    dockerfilePath: /filestash/Dockerfile
    dockerContext: /filestash
