services:
  - type: web
    name: filestash
    plan: 'starter plus'
    env: docker
    dockerfilePath: /filestash/Dockerfile
    dockerContext: /filestash
    domains:
      - filestash.mackenzieclark.codes
    disk:
      name: filestash
      mountPath: /app/data
      sizeGB: 25
