services:
  - type: web
    name: filestash
    plan: 'starter plus'
    env: docker
    repo: https://github.com/mickael-kerjean/filestash
    dockerfilePath: /docker/Dockerfile
    dockerContext: /docker
    domains:
      - filestash.mackenzieclark.codes
    disk:
      name: nextcloud
      mountPath: /app/data
      sizeGB: 25
