databases:
  - name: nextcloud
    plan: starter

services:
  - type: web
    name: nextcloud
    plan: 'starter plus'
    env: docker
    repo: https://github.com/nextcloud/docker.git
    dockerfilePath: ./18.0/apache/Dockerfile
    dockerContext: ./18.0/apache/
    disk:
      name: data
      mountPath: /var/www/html
    envVars:
      - key: POSTGRES_USER
        fromDatabase:
          name: nextcloud
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: nextcloud
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: nextcloud
          property: database
      - key: POSTGRES_HOST
        fromDatabase:
          name: nextcloud
          property: host
      - key: NEXTCLOUD_ADMIN_USER
        sync: false
      - key: NEXTCLOUD_ADMIN_PASSWORD
        sync: false
