services:
  - type: web
    name: filestash-oidc-proxy
    repo: https://github.com/xmclark/mackenzieclark.codes2
    dockerfilePath: ./filestash-oidc-proxy/Dockerfile
    dockerContext: ./filestash-oidc-proxy
    env: docker
    domains:
      - filestash.mackenzieclark.codes
    envVars:
      - key: OAUTH2_PROXY_CLIENT_ID
        sync: false
      - key: OAUTH2_PROXY_UPSTREAMS
        sync: false
      - key: OAUTH2_PROXY_REVERSE_PROXY
        value: true
      - key: OAUTH2_PROXY_PROVIDER
        value: oidc
      - key: OAUTH2_PROXY_CLIENT_SECRET
        sync: false
      - key: OAUTH2_PROXY_OIDC_ISSUER_URL
        sync: false
      - key: OAUTH2_PROXY_COOKIE_SECURE
        value: true
      - key: OAUTH2_PROXY_COOKIE_SECRET
        sync: false
      - key: OAUTH2_PROXY_EMAIL_DOMAINS
        value: '*'
      - key: OAUTH2_PROXY_HTTP_ADDRESS
        value: '0.0.0.0:4180'

  - type: pserv
    name: filestash
    plan: 'starter plus'
    env: docker
    dockerfilePath: /filestash/Dockerfile
    dockerContext: /filestash
