services:
  - type: web
    name: nextcloud
    env: docker
    repo: https://github.com/nextcloud/docker.git
    dockerfilePath: ./18.0/apache/Dockerfile
    dockerContext: ./18.0/apache/
    disk:
      name: data
      mountPath: /var/www/html
